### ISSUE TITLE
Only remove utm_ parameters

### ISSUE THREAD

**Issue by Njol** [rik/au-revoir-utm#1]
From looking at the source (3 lines of code, but whatever) I can tell that this addon won't work as expected. It only removes the utm stuff if the query string starts with an utm parameter (i.e. like "http://something.com?utm_...", but not "...?page=main&utm_..."), and it removes ALL parameters from the URL, not just the utm params.

Please fix this, as it seems like a quite useful addon otherwise.

**Comment by rik** [comment]
The [new version](https://addons.mozilla.org/en-US/firefox/addon/au-revoir-utm/) is now online and only removes `utm_` paramaters.
