### ISSUE TITLE
Support multiprocess Firefox

### ISSUE THREAD

**Issue by pquentin** [rik/au-revoir-utm#11]
When I enabled this extension, e10s is disabled. Is there anything to change in the extension to keep using it with e10s?

Thanks

**Comment by rik** [comment]
I'm currently rewriting this into a Web Extension so that will solve that issue.

**Comment by rik** [comment]
The [new version](https://addons.mozilla.org/en-US/firefox/addon/au-revoir-utm/) is now online

**Comment by pquentin** [comment]
Thank you!
