### ISSUE TITLE
Bug on Fredzone

### ISSUE THREAD

**Issue by Sykursen** [rik/au-revoir-utm#14]
Hello,
I've got a problem on the website **fredzone.com**
I receive articles by rss with an url like this [http://www.fredzone.org/la-terre-a-t-elle-ete-ensemencee-par-des-particules-extraterrestres-554#utm_source=feed&utm_medium=feed&utm_campaign=feed](http://www.fredzone.org/la-terre-a-t-elle-ete-ensemencee-par-des-particules-extraterrestres-554#utm_source=feed&utm_medium=feed&utm_campaign=feed) and the page don't load. But without utm_source, it's working.

An idea to fix that ?

**Comment by rik** [comment]
The issue was an infinite redirection. I've fixed and it will be in the next release.
