### ISSUE TITLE
Forwarding links don't work if URL contains utm parameters?

### ISSUE THREAD

**Issue by desigit** [rik/au-revoir-utm#16]
Hi, first-off, great add-on, super useful!

Just a small bug I found - when opening links such as the following in Firefox (which are created by Nuzzel.com's newsletters for example), then au-revoir stops that page from ever loading. When disabling au-revoir the links load normally.

The issue appears to be the last part of the URL that Nuzzel adds- "%26utm_medium%3Demail%26utm_source%3Dnuzzel" 

When this string is removed from the URL, it opens as normal. 

I.e., http://www.example.org/?%26utm_medium%3Demail%26utm_source%3Dnuzzel

When replacing "%26" with "&", then the link works as normal, even with au-revoir enabled.

Anyone else also experiencing this or any thoughts on what in au-revoir could be causing this?

**Comment by jarredou** [comment]
same problem with facebook's l.php proxy URL if it contains "utm" data in firefox (57)
kind of problematic URLs : "_https://l.facebook.com/l.php?u=http%3A%2F%2F_ [...] _%3Futm_campaign%3D_ [...]"

The page will apparently load infinitely, but watching the network tab from devtools, no request is sent, and nothing happens.

**Comment by rik** [comment]
Can you test with the latest version (1.1.0)? [A recent fix](https://github.com/rik/au-revoir-utm/commit/5cc5017aedbc1446e46aeda2edbe753b9de455d9) should have also fixed this issue.

**Comment by protostork** [comment]
Wonderful stuff, sorry for the delay hadn't been on Git in a while - it now works! :)

**Comment by rik** [comment]
Great!
