### ISSUE TITLE
Wrong url like https://geektimes.ru/post/298161/#habracut=

### ISSUE THREAD

**Issue by fox0** [rik/au-revoir-utm#17]
Original link: https://geektimes.ru/post/298161/?utm_source=habrahabr&utm_medium=rss&utm_campaign=298161#habracut

Correct link: https://geektimes.ru/post/298161/#habracut

But the addition adds an extra sign equally after the hash.

au-revoir-utm 1.1.0

**Comment by Vaelatern** [comment]
Just tested and can't duplicate. Maybe this was fixed?

**Comment by fox0** [comment]
No.
Original link: https://habr.com/ru/post/483154/?utm_source=habrahabr&utm_medium=rss&utm_campaign=483154#habracut
Correct link: https://habr.com/ru/company/dcmiran/blog/483154/#habracut

v1.1.0: https://habr.com/ru/company/dcmiran/blog/483154/#habracut=

**Comment by Vaelatern** [comment]
It works correctly for me with v1.1.0.
