### ISSUE TITLE
Prevent Tracking ?

### ISSUE THREAD

**Issue by vinny86** [rik/au-revoir-utm#2]
Can the addon be modified so as to prevent tracking ?

**Comment by rik** [comment]
I'm rewriting this into a Web Extension and using webRequestBlocking. This will fix this issue.

**Comment by palant** [comment]
In fact, the platform has evolved and producing fake responses became possible a while ago - my comment here is very much outdated.

**Comment by rik** [comment]
The [new version](https://addons.mozilla.org/en-US/firefox/addon/au-revoir-utm/) is now online and prevents tracking.
