### ISSUE TITLE
Addon doesn't remove utm in hash tags

### ISSUE THREAD

**Issue by kud** [rik/au-revoir-utm#4]
Like this: http://bigbrowser.blog.lemonde.fr/2012/09/05/langue-morte-comment-dit-on-minijupe-en-latin/#xtor=RSS-32280322?utm_source=twitterfeed&utm_medium=twitter

**Comment by daraniya** [comment]
I will just confirm that here... https://www.washingtonpost.com/news/wonk/wp/2016/12/21/the-real-reason-you-cant-buy-whipped-cream-this-christmas/?utm_term=.0f990b128c9a

IT didn't remove this "UTM" from the URL

**Comment by rik** [comment]
This should now work in the new version of the extension (1.1.0)

**Comment by mathstuf** [comment]
I just tested this with 1.1.0 and I ended up with `http://bigbrowser.blog.lemonde.fr/2012/09/05/langue-morte-comment-dit-on-minijupe-en-latin/#xtor=RSS-32280322%3Futm_source%3Dtwitterfeed`.
