### ISSUE TITLE
au-revoir-utm causes logging API to be disabled

### ISSUE THREAD

**Issue by AdrianGaudebert** [Rik/au-revoir-utm#8]
When au-revoir-utm is activated in my Nightly, it causes the console to say: 

```
The Web Console logging API (console.log, console.info, console.warn, console.error) 
has been disabled by a script on this page.
```

Which, you will agree, is quite annoying when you're working on the Web. :)

**Comment by Rik** [comment]
That's weird, it's like the simplest Jetpack add-on possible. It just includes a script in the page and there's nothing special outside of this.

**Comment by AdrianGaudebert** [comment]
I forgot to mention it but it doesn't happen on release, only Nightly. I'm on Ubuntu 14.10, Nightly 37.0a1. 

Looking at the code, it seems very weird indeed. But the fact is there: if I disable au-revoir-utm in my browser, the logging API becomes accessible again. If you're positive it comes from somewhere else, I'd be interested in knowing where, because I like this addon a lot.

**Comment by Rik** [comment]
Could it be e10s ?

**Comment by AdrianGaudebert** [comment]
If I understood correctly e10s is turned on by switching ``browser.tabs.remote.autostart`` on in ``about:config``, and that value is false for me. So I guess e10s cannot be the culprit here.

**Comment by Rik** [comment]
I think it is browser.tabs.remote.autostart.1 nowadays. But you can tell if the tab titles are underlined and if the option is checked in Preferences > General.

**Comment by AdrianGaudebert** [comment]
Ugh, I was testing with my release browser... My bad. 

So you're right, it's the combination of e10s and this addon that causes this bug. If I turn off e10s or disable au-revoir-utm, it works again. If both are on, it shows the message in the first comment. However, I don't know where that leads us.

**Comment by Rik** [comment]
I see that with other Jetpack add-ons too. So it is a Firefox issue. Can you open a bug blocking [516752](https://bugzilla.mozilla.org/show_bug.cgi?id=516752)?

**Comment by AdrianGaudebert** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1118301. Thanks for the directions @Rik.
