### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by RyDroid** [rik/au-revoir-utm#9]
Hi.

It seems that there is no license information. A LICENSE or COPYING file would be useful to know the license easily.

Regards.

**Comment by deepj** [comment]
@RyDroid The info can be found in `package.json`. See https://github.com/rik/au-revoir-utm/blob/master/package.json

The license is http://www.wtfpl.net/

**Comment by RyDroid** [comment]
Ok, thanks.
